compile:
	g++ transformations.cc ../glad.c ../utils/stb_image.cc ../utils/texture.cc ../utils/EBO.cc ../utils/VAO.cc ../utils/VBO.cc ../utils/shader.cc -o transformations -lglfw
	./transformations

run:
	./transformations
